### ISSUE TITLE
my.cnf only accepted with key value pairs

### ISSUE THREAD

**Issue by bastischubert** [prometheus/mysqld_exporter#132] opened 2016-06-07 09:04 UTC
hi everyone,

the mysqld_exporter chokes on a my.cnf that does not only contain key/value pairs, but boolean switches as well:

```
[mysqld]
...
skip-host-cache
skip-name-resolve
```
produces an fatal error on starting the mysqld_exporter:
```
[root@db1 ~]# ./mysqld_exporter -config.my-cnf=/etc/my.cnf 
INFO[0000] Starting mysqld_exporter (version=, branch=, revision=)  source=mysqld_exporter.go:412
INFO[0000] Build context (go=go1.5.4, user=, date=)      source=mysqld_exporter.go:413
FATA[0000] failed reading ini file: key-value delimiter not found: skip-host-cache
  source=mysqld_exporter.go:419
```

**Comment by RichiH** [comment] 2016-06-07 09:10
FYI: This is master's HEAD; but this info should probably be printed in the info string as well ;)

**Comment by SuperQ** [comment] 2016-06-07 09:10
`[mysqld]` context is not used in the client as well, so if we're parsing those values and passing them to the mysql client that's also broken.

**Comment by SuperQ** [comment] 2016-06-07 09:12
@richih That comes from `github.com/prometheus/common/version`, so probably needs to be fixed there.

**Comment by roman-vynar** [comment] 2016-06-07 09:21
Looks like this is how `gopkg.in/ini.v1` parses ini files, it expects key=value.

I think this is not a good idea to pass the whole MySQL config `/etc/my.cnf` to the exporter.
The exporter reads only `host`, `user`, `password`, `socket` options from `[client]` section, so it's enough to have a short config with the credentials.

**Comment by grobie** [comment] 2016-06-07 09:22
You need to set the respective ldflags. That's already done it building
with `make build` instead of a pain `go build`.

**Comment by SuperQ** [comment] 2016-06-07 09:23
This error is coming from our use of `gopkg.in/ini.v1` (https://github.com/go-ini/ini).  I'm not sure this library supports non key/value boolean flags the way MySQL uses them.  Unfortunately I think I'm going to have to say can't fix, as it's an upstream issue with go-ini.

**Comment by RichiH** [comment] 2016-06-07 09:25
@SuperQ What about @roman-vynar 's suggestion?

What's the need for the full config in the first place?

**Comment by SuperQ** [comment] 2016-06-07 09:56
@richih: @roman-vynar is correct, we don't need or want the full config to be sent to the exporter.  But the way the go-ini code works, it reads the whole file with a Load() function and you pick which sections you want after it returns a config struct.  The code in the OP is crashing at the Load() which we have no control over.

**Comment by RichiH** [comment] 2016-06-07 10:01
@SuperQ So the workaround is a fake file with only the info we really really need and an [upstream issue](https://github.com/go-ini/ini/issues/53)

**Comment by RichiH** [comment] 2016-06-07 10:07
@SuperQ Or could you just pass the needed into into https://github.com/go-sql-driver/mysql#dsn-data-source-name and do away with ini parsing completely?

**Comment by roman-vynar** [comment] 2016-06-07 10:27
@RichiH go-sql-driver does not provide a config file option to pass so it is parsed there.

If you don't want to use the config file option, pass the credentials via env var `DATA_SOURCE_NAME`, see https://github.com/prometheus/mysqld_exporter#setting-the-mysql-servers-data-source-name

**Comment by SuperQ** [comment] 2016-06-07 11:22
This is not a bug in the mysqld_exporter, so I am going to close this.

For the original requester:
* Use a `[client]` only my.cnf.
* Use the DATA_SOURCE_NAME env method.

**Closed by SuperQ** 2016-06-07 11:22 UTC

**Comment by komronu** [comment] 2022-06-10 17:29
[client]
user='exporter'
password='passw0rd'
host='127.0.0.1'
port='3306'


my config

**Comment by komronu** [comment] 2022-06-10 17:29
it's working
