### ISSUE TITLE
Release for Gentoo ?

### ISSUE THREAD

**Issue by ouraios** [prometheus/mysqld_exporter#186] opened 2017-02-28 16:07 UTC
Hi,
I'd like to know if it was possible to have a release for gentoo distribution ?

because when i use the linux amd64 release in my gentoo distribution it's taking a really long time to get metrics (5min)

Thanks in advance.

**Comment by brian-brazil** [comment] 2017-02-28 16:42
The linux amd64 release is the right release (presuming you're on a 64bit machine). The issue is likely with the mysqld itself, or the queries you've asked the exporter to run against it.

**Comment by ouraios** [comment] 2017-02-28 16:45
that's strange because my mysql server is working fine and effectively

**Comment by SuperQ** [comment] 2017-03-01 07:31
This sounds like a timeout somewhere, maybe DNS.

Are you running the `mysqld_exporter` on localhost?
What flags are you running the exporter with?

**Comment by ouraios** [comment] 2017-03-01 08:59
I run the mysqld_exporter with  theses flags : 
```-collect.binlog_size=true
-collect.info_schema.processlist=true
-config.my-cnf /home/deciplus/app/monitoring/mysqld_exporter/my.cnf```

What i dont understand is that when i run the binarty it takes at least 5 minutes before displaying "listening on port 9104" so i dont think it's something wrong with the mysql connection but with the binary itself on my operating system but i dont know what it can be, i use the linux amd64 and i'm using Gentoo amd64 which is based on GNU/Linux ...

**Comment by l-joseph** [comment] 2017-03-01 11:00
Ok i've just found out what was wrong !

On my server i have hundreds of databases with dozens of tables for each database.

SO it took a long time to read information_schema.tables and this is what was wrong.

I juste set collect.info_schema.tables flags to false and now it's completely fast ! 

Wonderful work you've done on this mysqld_exporter guys and thanks for your help ! I hope my solution will help some people having the same problem :)

**Comment by ouraios** [comment] 2017-03-01 11:00
Ok i've just found out what was wrong !

On my server i have hundreds of databases with dozens of tables for each database.

SO it took a long time to read information_schema.tables and this is what was wrong.

I juste set collect.info_schema.tables flags to false and now it's completely fast ! 

Wonderful work you've done on this mysqld_exporter guys and thanks for your help ! I hope my solution will help some people having the same problem :)

**Comment by SuperQ** [comment] 2017-03-01 16:15
Ah, yes, that endpoint can be very expensive on older versions of MySQL, This problem is fixed in MySQL 5.6 if I remember correctly.

Thanks for reporting the fix.

**Closed by SuperQ** 2017-03-01 16:15 UTC
Labels: help wanted

**Comment by sowndarya22** [comment] 2020-02-14 21:16
I have installed mysql_exporter on my Gentoo server. I could see only 4 metrics for MySQL from Prometheus, is this normal? Please let me know

**Comment by sowndarya22** [comment] 2020-02-14 21:26
If you have can U please provide init.d script for mysql_exporter

**Comment by SuperQ** [comment] 2020-02-15 10:29
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
